---
name: CI

on: [pull_request]

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          make install-infra-build-tools
          pip install ansible
          ansible-galaxy install -r base-ami/ansible/requirements.yml
        
